package mtproto


const (
	PEER_TYPE_USER    = "USER"
	PEER_TYPE_CHAT    = "CHAT"
	PEER_TYPE_CHANNEL = "CHANNEL"
)

const (
	DIALOG_TYPE_CHAT    = "CHAT"
	DIALOG_TYPE_USER    = "USER"
	DIALOG_TYPE_CHANNEL = "CHANNEL"
)

const (
	USER_STATUS_OFFLINE    = "OFFLINE"
	USER_STATUS_ONLINE     = "ONLINE"
	USER_STATUS_RECENTLY   = "RECENTLY"
	USER_STATUS_LAST_WEEK  = "LAST_WEEK"
	USER_STATUS_LAST_MONTH = "LAST_MONTH"
)

const (
	MESSAGE_TYPE_EMPTY     = "EMPTY"
	MESSAGE_TYPE_NORMAL    = "NORMAL"
	MESSAGE_TYPE_SERVICE   = "SERVICE"
	MESSAGE_TYPE_FORWARDED = "FORWARDED"
)

const (
	MESSAGE_ACTION_CHAT_CREATED         = "CHAT_CREATED"
	MESSAGE_ACTION_CHAT_EDIT_TITLE      = "CHAT_EDIT_TITLE"
	MESSAGE_ACTION_CHAT_EDIT_PHOTO      = "CHAT_EDIT_PHOTO"
	MESSAGE_ACTION_CHAT_DELETE_PHOTO    = "CHAT_DELETE_PHOTO"
	MESSAGE_ACTION_CHAT_ADD_USER        = "CHAT_ADD_USER"
	MESSAGE_ACTION_CHAT_DELETE_USER     = "CHAT_DELETE_USER"
	MESSAGE_ACTION_CHAT_JOINED_BY_LINK  = "CHAT_JOINED_BY_LINK"
	MESSAGE_ACTION_CHAT_MIGRATE_TO      = "CHAT_MIGRATE_TO"
	MESSAGE_ACTION_CHANNEL_CREATED      = "CHANNEL_CREATED"
	MESSAGE_ACTION_CHANNEL_MIGRATE_FROM = "CHANNEL_MIGRATE"
	MESSAGE_ACTION_GAME_SCORE           = "GAME_SCORE"
	MESSAGE_ACTION_HISTORY_CLEAN        = "HISTORY_CLEAN"
)

const (
	MESSAGE_MEDIA_TYPE_EMPTY    = "EMPTY"
	MESSAGE_MEDIA_TYPE_PHOTO    = "PHOTO"
	MESSAGE_MEDIA_TYPE_VIDEO    = "VIDEO"
	MESSAGE_MEDIA_TYPE_GEO      = "GEO"
	MESSAGE_MEDIA_TYPE_CONTACT  = "CONTACT"
	MESSAGE_MEDIA_TYPE_DOCUMENT = "DOCUMENT"
	MESSAGE_MEDIA_TYPE_AUDIO    = "AUDIO"
)